version: '3'

services:
  db:
    image: mysql
    container_name: db-to-do-list
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: to_do_list
    volumes: 
      - ./db/data:/var/lib/mysql
    restart: always

  backend:
    build: "./backend"
    container_name: backend-to-do-list
    command: php artisan serve
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: "./frontend"
    container_name: frontend-to-do-list
    command: ionic serve
    restart: always
    volumes:
      - ./frontend:/app
    ports: 
      - "8100:8100"
    depends_on:
      - backend
