name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: Setup Enviroment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        
    - name: Speed up the packages installation process
      run: composer global require hirak/prestissimo
    
    - name: Install Packages
      run: composer install --no-dev
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.rawlinsonrolimadv.com
        username: mnradv76
        password: MACAhell2704
        local-dir: './backend/'
        server-dir: '/teste.rawlinsonrolimadv.com/'
        exclude: |
          **/.git*
          **/.git*/**
          **/vendor/**
          **/.env
