name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      
      #- name: Configure PHP
      #  uses: shivammathur/setup-php@v2
      #  with:
      #    php-version: 8.0
      #    extensions: mbstring, ctype, fileinfo, openssl, PDO, json, xml, tokenizer, bcmath
      #- name: Install composer dependencies
      #  run: | 
      #    cd ./backend
      #    composer update
      #- name: Copy .ENV
      #  run: |
      #    cd ./backend
      #    cp .env.example .env
      #- name: Generate key for laravel
      #  run: |
      #    cd ./backend
      #    php artisan key:generate

      - name: Upload Ftp
        uses: airvzxf/ftp-deployment-action@latest
        with: 
          server: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./backend/"
          remote_dir: "/teste.rawlinsonrolimadv.com/"