name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: "ubuntu-20.04"

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammatur/setup-php@master
        with:
          php-version: "8.0"
          extensions: mbstring, ctype, fyleinfo, openssl
      
  deploy:
    name: 🎉 Deploy
    runs-on: "ubuntu-20.04"

    steps:
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './backend/'
          server-dir: '/teste.rawlinsonrolimadv.com/'
