name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      
      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-cersion: 8.0
          extensions: mbstring, ctype, fileinfo, openssl, PDO, json, xml, tokenizer, bcmath
      
      - name: Install composer dependencies
        run: | 
          cd ./backend
          composer install
          cp .env.example .env
      
  
